using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace TenderAssistant.Client.Controls;

public static class MaterialDataGridColumns
{
    public static readonly DependencyProperty UseBusinessColumnsProperty = DependencyProperty.RegisterAttached(
        "UseBusinessColumns",
        typeof(bool),
        typeof(MaterialDataGridColumns),
        new PropertyMetadata(false, OnUseBusinessColumnsChanged));

    private static readonly Dictionary<string, ColumnDefinition> Columns = new(StringComparer.Ordinal)
    {
        ["Status"] = new("状态", 40, 100),
        ["FileName"] = new("文件名", 10, 220),
        ["FileTypeText"] = new("类型", 20, 70),
        ["PageCountText"] = new("页数", 30, 70),
        ["SizeText"] = new("大小", 40, 80),
        ["LastModified"] = new("修改时间", 50, 140, "yyyy-MM-dd HH:mm"),
        ["OccurredAt"] = new("时间", 5, 150, "yyyy-MM-dd HH:mm:ss"),
        ["TargetSoftware"] = new("目标软件", 30, 100),
        ["Result"] = new("结果", 40, 80),
        ["Message"] = new("内容", 50, 260),
        ["Level"] = new("级别", 20, 80),
        ["Category"] = new("分类", 30, 100),
        ["Action"] = new("操作", 40, 120),
        ["CreatedAt"] = new("创建时间", 20, 150, "yyyy-MM-dd HH:mm:ss"),
        ["Size"] = new("大小", 30, 90)
    };

    private static readonly DependencyProperty DesiredDisplayIndexProperty = DependencyProperty.RegisterAttached(
        "DesiredDisplayIndex",
        typeof(int),
        typeof(MaterialDataGridColumns),
        new PropertyMetadata(int.MaxValue));

    public static bool GetUseBusinessColumns(DependencyObject obj)
    {
        return (bool)obj.GetValue(UseBusinessColumnsProperty);
    }

    public static void SetUseBusinessColumns(DependencyObject obj, bool value)
    {
        obj.SetValue(UseBusinessColumnsProperty, value);
    }

    private static void OnUseBusinessColumnsChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is not DataGrid dataGrid)
        {
            return;
        }

        dataGrid.AutoGeneratingColumn -= OnAutoGeneratingColumn;
        dataGrid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
        if (e.NewValue is true)
        {
            dataGrid.AutoGeneratingColumn += OnAutoGeneratingColumn;
            dataGrid.AutoGeneratedColumns += OnAutoGeneratedColumns;
        }
    }

    private static void OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        if (!Columns.TryGetValue(e.PropertyName, out var definition))
        {
            e.Cancel = true;
            return;
        }

        e.Column.Header = definition.Header;
        e.Column.SetValue(DesiredDisplayIndexProperty, definition.DisplayIndex);
        e.Column.Width = new DataGridLength(definition.Width);

        if (!string.IsNullOrWhiteSpace(definition.StringFormat)
            && e.Column is DataGridBoundColumn boundColumn
            && boundColumn.Binding is Binding binding)
        {
            binding.StringFormat = definition.StringFormat;
        }
    }

    private static void OnAutoGeneratedColumns(object? sender, EventArgs e)
    {
        if (sender is not DataGrid dataGrid)
        {
            return;
        }

        var orderedColumns = dataGrid.Columns
            .OrderBy(static column => (int)column.GetValue(DesiredDisplayIndexProperty))
            .ThenBy(static column => column.Header?.ToString(), StringComparer.CurrentCulture)
            .ToArray();

        for (var index = 0; index < orderedColumns.Length; index++)
        {
            orderedColumns[index].DisplayIndex = index;
        }
    }

    private sealed record ColumnDefinition(string Header, int DisplayIndex, double Width, string? StringFormat = null);
}
